### ISSUE TITLE
TLS broken by PR #33

### ISSUE THREAD

**Issue by ioben** [minio/charts#40]
It looks like PR #33 made a change which doesn't work correctly with Helm's logic (though it looks like it should). The PR should be reverted.

Here's an example chart to demonstrate the issue:

`test-chart/Chart.yaml`:
```
version: 0.0.1
name: test
```

`test-chart/templates/test-file.yml`:
```
---
apiVersion: v1
kind: Service
{{- $scheme := "http" -}}
{{- if .Values.enabled }}
test: test
{{- $scheme := "https" -}}
{{ end }}
test: {{ $scheme }}
```

The above `test-file.yml` has the bug in it.

Running `helm template test-chart --set enabled=false`:

```
---
# Source: test/templates/test-file.yml
apiVersion: v1
kind: Service
test: http
```

Running `helm template test-chart --set enabled=true`:

```
---
# Source: test/templates/test-file.yml
apiVersion: v1
kind: Service
test: test
test: http
```

You can see `test: test` is outputted, which implies the if conditional was triggered; but `test: http` is still shown, `$scheme` was never updated. Counterintuitively, `$scheme = "https"` (no `:`) is correct within a conditional. After making that change, the `helm template` outputs the expected value. I tested this in Helm `2.16.9`, `3.3.1`, `3.3.4` and got the above results.

I'm confused, because another user of the chart mentioned it fixed their issue in the original PR.

**Comment by laszlojau** [comment]
I tried deploying in distributed mode with TLS today and it failed due to this issue. Checking the arguments for `command` in the StatefulSet, I could see that it was pointing to `http://`.

I believe @ioben is right. In Go templating `:=` is used for short declaration.
The `$scheme` variable is already declared at [minio/template/statefulset.yml Line 5](https://github.com/minio/charts/blob/fe46d0cdf8cd7054aac12cc6870a3416ebc2a6cc/minio/templates/statefulset.yaml#L5): `{{ $scheme := "http" }}`

I'm not sure what syntax error the user was facing that the mentioned PR fixed, but doing `{{ $scheme := "https" }}` doesn't seem to take effect.

If I was to do something similar in Go, it would throw an error. E.g.:
```
$ cat test.go

package main
import "fmt"

func main() {
  scheme := "http"
  fmt.Println(scheme)
  scheme := "https"
  fmt.Println(scheme)
}

$ go run test.go
# command-line-arguments
./test.go:7:10: no new variables on left side of :=
```

vs
```
$ cat test.go

package main
import "fmt"

func main() {
  scheme := "http"
  fmt.Println(scheme)
  scheme = "https"
  fmt.Println(scheme)
}

$ go run test.go
# command-line-arguments
http
https
```

PR #33 should be reverted to fix this issue.

**Comment by harshavardhana** [comment]
> $ cat test.go
> 
> package main
> import "fmt"
> 
> func main() {
>   scheme := "http"
>   fmt.Println(scheme)
>   scheme := "https"
>   fmt.Println(scheme)
> }
> 
> $ go run test.go
> # command-line-arguments
> ./test.go:7:10: no new variables on left side of :=

This is a bogus test case @laszlojau - helm is a template engine, not a Go program. 

> Running `helm template test-chart --set enabled=true`:

You need to do `--set tls.enabled=true` @ioben  but yes I was able to reproduce and fix this.
